#!/bin/bash

echo "🔄 GTPC Website - GitHub Sync Guide"
echo "==================================="
echo ""

echo "📋 Step 1: Create GitHub Repository"
echo "   1. Go to https://github.com"
echo "   2. Click 'New repository'"
echo "   3. Repository name: gtpc-website"
echo "   4. Make it Public"
echo "   5. DON'T initialize with README"
echo "   6. Click 'Create repository'"
echo ""

echo "📤 Step 2: Upload Code to GitHub"
echo "   Run these commands in Replit Shell:"
echo ""
echo "   git add ."
echo "   git commit -m 'Complete GTPC website with legal pages'"
echo "   git remote add origin https://github.com/YOUR_USERNAME/gtpc-website.git"
echo "   git push -u origin main"
echo ""

echo "🔄 Step 3: Future Syncing"
echo ""
echo "   FROM REPLIT TO GITHUB:"
echo "   git add ."
echo "   git commit -m 'Your changes description'"
echo "   git push"
echo ""
echo "   FROM GITHUB TO REPLIT:"
echo "   git pull"
echo ""

echo "⚙️ Step 4: Automatic Sync (Optional)"
echo "   The GitHub Actions we created will automatically:"
echo "   - Sync your Replit changes to GitHub"
echo "   - Deploy to your live website"
echo ""

echo "💡 Pro Tips:"
echo "   - Always commit with descriptive messages"
echo "   - Pull before making new changes if working from multiple places"
echo "   - The .github/workflows will handle deployment automatically"
echo ""

echo "🎯 Your workflow will be:"
echo "   1. Make changes in Replit"
echo "   2. Commit and push to GitHub"
echo "   3. Website automatically updates!"